# Deployment da aplicação web
apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao-temperatura
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: conversao-temperatura
  template:
    metadata:
      labels:
        app: conversao-temperatura
    spec:
      containers:
        - name: conversao-temperatura
          image: ghcr.io/claudi0s0uza/conversao-temperatura
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports: 
            - containerPort: 8080
--- 
# Service da aplicação web
apiVersion: v1
kind: Service
metadata:
  name: conversao-temperatura
spec: 
  selector:
    app: conversao-temperatura
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30010
  type: LoadBalancer
