name: CI-CD

on:
  workflow_dispatch:
  


jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: azure/docker-login@v1
      with:
        login-server: ghcr.io
        username: ${{ secrets.GH_PACKAGES_USER }}
        password: ${{ secrets.GH_PACKAGES_TOKEN }}
    
    - run: |
        docker build -t ghcr.io/claudi0s0uza/conversao-temperatura:latest -f ./src/Dockerfile .
        docker tag ghcr.io/claudi0s0uza/conversao-temperatura:latest ghcr.io/claudi0s0uza/conversao-temperatura:${{ github.sha }}
    
    - run: |
        docker push ghcr.io/claudi0s0uza/conversao-temperatura:latest
        docker push ghcr.io/claudi0s0uza/conversao-temperatura:${{ github.sha }}

  CD:
    needs: [CI]
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        
      - name: Kubernetes set context
        uses: Azure/k8s-set-context@v1.1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.K8S_CONFIG }}
      
      - name: Deploy to Kubernetes cluster
        uses: Azure/k8s-deploy@v1.3
        with: 
          images: ghcr.io/claudi0s0uza/conversao-temperatura:${{ github.sha }} 
          manifests: |
              k8s/deployment.yaml
